import type { Service, ServiceCategory, Event } from "@/types/database";

export const sampleCategories: ServiceCategory[] = [
  {
    id: "cat-1",
    name: "Homam / Havan",
    slug: "homam-havan",
    description: "Sacred fire rituals and offerings to deities through Agni",
    icon: "🔥",
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Pooja & Samskaras",
    slug: "pooja-samskaras",
    description: "Traditional worship rituals, prayers, and Sodash Samskaras",
    icon: "🙏",
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "Kalyanotsavam & Vivaham",
    slug: "kalyanotsavam-vivaham",
    description: "Divine and traditional wedding ceremonies",
    icon: "💒",
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Paaraayana & Vratams",
    slug: "paaraayana-vratams",
    description: "Sacred recitations, fasting, and religious observances",
    icon: "📿",
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    name: "Jyotisham & Vastu",
    slug: "jyotisham-vastu",
    description: "Vedic astrology, Vastu consultation, and Muhoortham",
    icon: "⭐",
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-6",
    name: "Sharadham & Remedial",
    slug: "sharadham-remedial",
    description: "Sharadham ceremonies and remedial yagnas",
    icon: "🙏",
    sort_order: 6,
    created_at: new Date().toISOString(),
  },
];

export const sampleServices: Service[] = [
  // Pooja & Samskaras
  {
    id: "svc-1",
    category_id: "cat-2",
    name: "Ganapathi Pooja",
    slug: "ganapathi-pooja",
    short_description: "Sacred worship of Lord Ganesha, the remover of obstacles.",
    full_description: "Ganapathi Pooja is performed to invoke the blessings of Lord Ganesha before any auspicious event or new beginning. This pooja is traditionally performed first in all Hindu rituals.",
    significance: "Lord Ganesha removes obstacles and grants success, prosperity, and wisdom.",
    items_to_bring: ["Modak or laddoo", "Coconut", "Durva grass", "Red flowers"],
    whats_included: ["Complete pooja", "Sankalpam", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 60,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-2",
    category_id: "cat-2",
    name: "Punyaahavaachanam",
    slug: "punyaahavaachanam",
    short_description: "Sacred purification ceremony for sanctifying a space or occasion.",
    full_description: "Punyaahavaachanam is a Vedic purification ritual that sanctifies the environment and the participants before major ceremonies or life events.",
    significance: "This ritual purifies the surroundings and participants, making them spiritually ready for auspicious ceremonies.",
    items_to_bring: ["Holy water", "Turmeric", "Kumkum"],
    whats_included: ["Complete purification ritual", "Mantras", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 45,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-3",
    category_id: "cat-2",
    name: "Namakaranam",
    slug: "namakaranam",
    short_description: "Traditional Hindu naming ceremony for newborns.",
    full_description: "Namakaranam is one of the Sodash Samskaras — the sacred naming ceremony performed for a newborn child, typically on the 11th or 12th day after birth.",
    significance: "The naming ceremony invokes divine blessings for the child's long life, health, and prosperity.",
    items_to_bring: ["New clothes for baby", "Gold ornament", "Honey"],
    whats_included: ["Complete naming ritual", "Horoscope consultation", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 60,
    location_type: "both",
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-4",
    category_id: "cat-2",
    name: "Upanayanam",
    slug: "upanayanam",
    short_description: "Sacred thread ceremony marking the beginning of Vedic education.",
    full_description: "Upanayanam is a major Samskara in Hindu tradition, marking the initiation of a boy into Vedic studies. The ceremony involves the investiture of the sacred thread (Yagnopaveetam).",
    significance: "This ceremony marks the spiritual rebirth and beginning of the student's journey into Vedic knowledge.",
    items_to_bring: ["Sacred thread", "New clothes", "Coconut", "Ghee"],
    whats_included: ["Complete Upanayanam ceremony", "Gayatri mantra initiation", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-5",
    category_id: "cat-2",
    name: "Gruhapravesam",
    slug: "gruhapravesam",
    short_description: "Housewarming ceremony to purify and bless a new home.",
    full_description: "Gruhapravesam is the sacred ceremony of entering a new home. The ritual includes Ganapathi Pooja, Vastu Pooja, Navagraha Pooja, and Havan to cleanse and energize the new home.",
    significance: "This ceremony removes negative energies, invites prosperity, health, and happiness into the new home.",
    items_to_bring: ["New pot with mango leaves", "Rice", "Turmeric and kumkum", "Milk to boil", "Coconuts"],
    whats_included: ["Ganapathi Pooja", "Vastu Pooja", "Navagraha Shanti", "Havan", "Milk boiling ceremony"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "outside_temple",
    is_active: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-6",
    category_id: "cat-2",
    name: "Satyanaaraayana Pooja",
    slug: "satyanarayana-pooja",
    short_description: "Sacred worship of Lord Satyanarayana with Katha recitation.",
    full_description: "Sri Satyanarayana Pooja involves worshipping Lord Vishnu in the form of Satyanarayana, followed by reading the five chapters of the Satyanarayana Katha. Commonly performed for housewarmings, weddings, and milestones.",
    significance: "This pooja bestows blessings of prosperity, harmony, and fulfillment.",
    items_to_bring: ["Banana leaves", "Fruits and flowers", "Ripe bananas", "Jaggery and wheat flour"],
    whats_included: ["Pooja and Katha recitation", "All pooja materials", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Kalyanotsavam & Vivaham
  {
    id: "svc-7",
    category_id: "cat-3",
    name: "Rama Kalyanam",
    slug: "rama-kalyanam",
    short_description: "Divine celestial wedding ceremony of Lord Rama and Goddess Sita.",
    full_description: "Experience the divine wedding of Lord Rama and Goddess Sita, one of the most beautiful and auspicious ceremonies in Hindu tradition.",
    significance: "Witnessing the divine wedding brings marital harmony, blessings for family life, and spiritual merit.",
    items_to_bring: ["Flowers and garlands", "Fruits", "New clothes for deities (optional)"],
    whats_included: ["Complete wedding ceremony", "Deity decoration", "Talambralu", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-8",
    category_id: "cat-3",
    name: "Srinivasa Kalyanam",
    slug: "srinivasa-kalyanam",
    short_description: "Divine wedding ceremony of Lord Srinivasa and Goddess Padmavathi.",
    full_description: "Srinivasa Kalyanam recreates the celestial wedding of Lord Venkateswara (Srinivasa) and Goddess Padmavathi with elaborate Vedic rituals.",
    significance: "This divine wedding ceremony brings blessings of love, prosperity, and family harmony.",
    items_to_bring: ["Flowers and garlands", "Fruits", "Coconuts"],
    whats_included: ["Complete Kalyanam ceremony", "Deity decoration", "Prasadam feast"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-9",
    category_id: "cat-3",
    name: "Vivaham (Wedding)",
    slug: "vivaham",
    short_description: "Traditional Hindu wedding ceremony performed with Vedic rituals.",
    full_description: "A complete traditional Hindu wedding ceremony including Snathakam, Kashi Yatra, Kanyadaanam, Mangalsutra Dharanam, Saptapadi, and all traditional rituals.",
    significance: "The Vedic wedding ceremony sanctifies the union of two souls and families with divine blessings.",
    items_to_bring: ["Wedding attire", "Mangalsutra", "Turmeric", "All ritual items (list provided)"],
    whats_included: ["Complete wedding ceremony", "Snathakam", "All Vedic rituals", "Guidance on arrangements"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 240,
    location_type: "both",
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Homam / Havan
  {
    id: "svc-10",
    category_id: "cat-1",
    name: "Ganapathi Homam",
    slug: "ganapathi-homam",
    short_description: "Fire ritual dedicated to Lord Ganesha for removing obstacles and new beginnings.",
    full_description: "Ganapathi Homam is a sacred fire ritual performed to invoke the blessings of Lord Ganesha. This is typically the first homam performed before any auspicious event.",
    significance: "Removes obstacles, grants success in endeavors, and brings prosperity and wisdom.",
    items_to_bring: ["Modak or laddoo (21 pieces)", "Coconut", "Durva grass", "Red flowers"],
    whats_included: ["Complete fire ritual", "All homa materials", "Sankalpam", "Purnahuti", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-11",
    category_id: "cat-1",
    name: "Navagraha Homam",
    slug: "navagraha-homam",
    short_description: "Fire ritual to appease the nine planetary deities. Includes Japam, Rahu Ketu Puja, Kalasarpa Shanti.",
    full_description: "Navagraha Homam is a powerful fire ritual to propitiate the nine celestial bodies. Select from: Japam, Rahu Ketu Puja, or Kalasarpa Shanti.",
    significance: "Balances planetary influences, brings harmony, good health, and prosperity.",
    items_to_bring: ["9 types of grains", "9 types of flowers", "Coconut", "Ghee"],
    whats_included: ["Full Navagraha ritual", "All homa materials", "Individual planet mantras", "Purnahuti", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-12",
    category_id: "cat-1",
    name: "Sudarsana Homam",
    slug: "sudarsana-homam",
    short_description: "Fire ritual invoking Lord Sudarshana for protection from negative energies.",
    full_description: "Sudarsana Homam is performed to invoke the powerful Sudarshana Chakra of Lord Vishnu for protection, removal of evil eye, and overcoming obstacles.",
    significance: "Provides divine protection, removes negative energies, and brings peace.",
    items_to_bring: ["Coconut", "Ghee", "Flowers"],
    whats_included: ["Complete Sudarsana ritual", "All homa materials", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-13",
    category_id: "cat-1",
    name: "Rudra Homam",
    slug: "rudra-homam",
    short_description: "Powerful fire ritual dedicated to Lord Shiva for health, prosperity, and spiritual growth.",
    full_description: "Rudra Homam is one of the most powerful Vedic fire rituals dedicated to Lord Shiva. It is performed for health, longevity, removal of diseases, and spiritual upliftment.",
    significance: "Invokes Lord Shiva's blessings for health, prosperity, and liberation from karmic bonds.",
    items_to_bring: ["Bilva leaves", "Rudraksha", "Ghee", "Coconut"],
    whats_included: ["Complete Rudra Homam", "All homa materials", "Rudra Abhishekam", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-14",
    category_id: "cat-1",
    name: "Mrutyunjaya Homam",
    slug: "mrutyunjaya-homam",
    short_description: "Fire ritual for longevity, health, and overcoming serious illnesses.",
    full_description: "Mrutyunjaya Homam is dedicated to Lord Shiva in his Mrutyunjaya form. It is performed for recovery from illness, longevity, and protection from untimely death.",
    significance: "Bestows health, longevity, and protection. Especially performed during health crises.",
    items_to_bring: ["Ghee", "Sesame seeds", "Bilva leaves", "Durva grass"],
    whats_included: ["Complete Mrutyunjaya ritual", "All homa materials", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-15",
    category_id: "cat-1",
    name: "Lakshmi Homam",
    slug: "lakshmi-homam",
    short_description: "Fire ritual to invoke Goddess Lakshmi for wealth and prosperity.",
    full_description: "Lakshmi Homam is performed to invoke the blessings of Goddess Lakshmi for wealth, prosperity, and abundance.",
    significance: "Brings financial stability, prosperity, and removes poverty.",
    items_to_bring: ["Lotus flowers", "Ghee", "Coconut", "Turmeric"],
    whats_included: ["Complete Lakshmi Homam", "All homa materials", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-16",
    category_id: "cat-1",
    name: "Chandi Homam",
    slug: "chandi-homam",
    short_description: "Powerful fire ritual invoking Goddess Durga for protection and victory.",
    full_description: "Chandi Homam is a powerful ritual invoking Goddess Durga/Chandi for protection, victory over enemies, and removal of obstacles in life.",
    significance: "Invokes divine feminine power for protection, courage, and success.",
    items_to_bring: ["Red flowers", "Ghee", "Coconut", "Kumkum"],
    whats_included: ["Complete Chandi Homam", "All homa materials", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 150,
    location_type: "both",
    is_active: true,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Shiva Rudraabhishekam
  {
    id: "svc-17",
    category_id: "cat-2",
    name: "Shiva Rudraabhishekam",
    slug: "shiva-rudraabhishekam",
    short_description: "Sacred abhishekam of Lord Shiva with Rudram chanting. Multiple options available.",
    full_description: "Shiva Rudraabhishekam is available in multiple forms: Mahanayasa purvaka Ekavara Rudrabhishekam (1 time), Ekadasha Rudrabhishekam (11 times), Mahalingarchana (365 clay lingams), or Sahasra Lingarchana (1116 clay lingams).",
    significance: "Shiva Abhishekam with Rudram is one of the most powerful rituals for health, prosperity, and spiritual progress.",
    items_to_bring: ["Milk", "Honey", "Bilva leaves", "Ghee"],
    whats_included: ["Complete Rudraabhishekam", "Alankaram", "Archana", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Paaraayana & Vratams
  {
    id: "svc-18",
    category_id: "cat-4",
    name: "Sundarakaanda Paaraayana",
    slug: "sundarakaanda-paaraayana",
    short_description: "Complete recitation of Sundarakanda from the Ramayana.",
    full_description: "Sundarakaanda Paaraayana is the recitation of the 5th chapter of Valmiki Ramayana, detailing Hanuman's journey to Lanka.",
    significance: "Brings strength, courage, and resolution of problems. Especially beneficial for those facing obstacles.",
    items_to_bring: ["Flowers", "Fruits"],
    whats_included: ["Complete Paaraayana", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-19",
    category_id: "cat-4",
    name: "Bhagavadgeetha Paaraayana",
    slug: "bhagavadgeetha-paaraayana",
    short_description: "Complete recitation of the Bhagavad Gita.",
    full_description: "Full recitation of all 18 chapters of the Bhagavad Gita with proper intonation and meaning.",
    significance: "Brings clarity, spiritual wisdom, and peace of mind.",
    items_to_bring: ["Flowers", "Fruits"],
    whats_included: ["Complete Paaraayana", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Jyotisham & Vastu
  {
    id: "svc-20",
    category_id: "cat-5",
    name: "Jyotisham (Astrology)",
    slug: "jyotisham",
    short_description: "Vedic astrology consultation — horoscope reading, jathakam, and predictions.",
    full_description: "Get personalized Vedic astrology consultations including birth chart analysis, predictions, and guidance based on planetary positions.",
    significance: "Understanding planetary influences helps make informed decisions and plan important life events.",
    items_to_bring: ["Birth details (date, time, place)"],
    whats_included: ["Personal consultation", "Written report"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 60,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-21",
    category_id: "cat-5",
    name: "Muhoortham",
    slug: "muhoortham",
    short_description: "Auspicious date and time calculation for important life events.",
    full_description: "Get personalized Muhoortham calculations for weddings, griha pravesham, naming ceremonies, business openings, and other significant life events.",
    significance: "Starting important activities at an auspicious time ensures success and aligns your actions with cosmic energies.",
    items_to_bring: ["Birth details", "Preferred date range"],
    whats_included: ["Personal consultation", "Written Muhoortham report"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 60,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-22",
    category_id: "cat-5",
    name: "Vastu Consultation",
    slug: "vastu",
    short_description: "Vastu Shastra consultation for homes and businesses.",
    full_description: "Expert Vastu Shastra consultation to align your living or working space with cosmic energies for harmony, prosperity, and well-being.",
    significance: "Proper Vastu alignment brings positive energy flow, peace, and prosperity to the occupants.",
    items_to_bring: ["Floor plan of the property"],
    whats_included: ["On-site or remote consultation", "Detailed Vastu report", "Remedial suggestions"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Sharadham & Remedial
  {
    id: "svc-23",
    category_id: "cat-6",
    name: "Anna Sharadham w/ Homam",
    slug: "anna-sharadham",
    short_description: "Annual ancestral ceremony with fire ritual.",
    full_description: "Anna Sharadham is the annual ceremony performed in memory of departed ancestors, combined with a sacred Homam for their spiritual upliftment.",
    significance: "Honors departed ancestors and seeks their blessings for the family's well-being.",
    items_to_bring: ["Items as advised by priest"],
    whats_included: ["Complete Sharadham ceremony", "Homam", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-24",
    category_id: "cat-6",
    name: "Navagraha Shanthi",
    slug: "navagraha-shanthi",
    short_description: "Remedial ritual to pacify unfavorable planetary positions.",
    full_description: "Navagraha Shanthi is a comprehensive remedial ritual performed to pacify and balance the effects of all nine planets in one's horoscope.",
    significance: "Mitigates negative planetary effects and restores balance in life.",
    items_to_bring: ["Items as advised by priest"],
    whats_included: ["Complete Shanthi ritual", "All materials", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-25",
    category_id: "cat-2",
    name: "Bhoomi Pooja",
    slug: "bhoomi-pooja",
    short_description: "Ground-breaking ceremony before construction of a new building.",
    full_description: "Bhoomi Pooja is the sacred ceremony performed before breaking ground for construction. It seeks blessings from Mother Earth and divine energies.",
    significance: "Ensures safe construction, removes Vastu doshas, and invites prosperity to the new building.",
    items_to_bring: ["Items as advised by priest"],
    whats_included: ["Complete Bhoomi Pooja", "Vastu ritual", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "outside_temple",
    is_active: true,
    sort_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-26",
    category_id: "cat-2",
    name: "Business Openings",
    slug: "business-openings",
    short_description: "Sacred ceremony for inaugurating a new business.",
    full_description: "Special pooja and ceremony performed for the auspicious opening of a new business or office, invoking divine blessings for success and prosperity.",
    significance: "Ensures a blessed and prosperous start to the new business venture.",
    items_to_bring: ["Items as advised by priest"],
    whats_included: ["Complete inauguration ceremony", "Ganapathi Pooja", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 60,
    location_type: "outside_temple",
    is_active: true,
    sort_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const sampleEvents: Event[] = [
  {
    id: "evt-1",
    title: "Ugadi Celebrations 2026",
    description:
      "Telugu and Kannada New Year celebrations with special poojas, cultural programs, and festive feast. Join us for Panchangam Sravanam and Ugadi Pachadi distribution.",
    event_type: "festival",
    start_date: "2026-03-29",
    end_date: "2026-03-29",
    start_time: "09:00",
    end_time: "14:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 45,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-2",
    title: "Sri Rama Navami",
    description:
      "Celebration of Lord Rama's birth with Sita Rama Kalyanotsavam, Abhishekam, and special cultural programs throughout the day.",
    event_type: "festival",
    start_date: "2026-04-07",
    end_date: "2026-04-07",
    start_time: "08:00",
    end_time: "20:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 78,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-3",
    title: "Weekly Bhajan Sandhya",
    description:
      "Join us every Saturday evening for devotional bhajans and kirtans. All are welcome to participate and immerse in the divine melodies.",
    event_type: "regular_pooja",
    start_date: "2026-03-14",
    end_date: null,
    start_time: "18:00",
    end_time: "19:30",
    location: "RNHT Prayer Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-saturday",
    rsvp_enabled: false,
    rsvp_count: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-4",
    title: "Yoga & Meditation Session",
    description:
      "Weekly yoga and meditation classes suitable for all levels. Guided by certified instructors combining traditional and modern techniques.",
    event_type: "class",
    start_date: "2026-03-15",
    end_date: null,
    start_time: "07:00",
    end_time: "08:30",
    location: "RNHT Community Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-sunday",
    rsvp_enabled: true,
    rsvp_count: 22,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-5",
    title: "Monthly Satyanarayana Vratam",
    description:
      "Join the community for the monthly Satyanarayana Pooja on Purnima (Full Moon) day. Katha recitation followed by maha prasadam.",
    event_type: "regular_pooja",
    start_date: "2026-03-25",
    end_date: null,
    start_time: "10:00",
    end_time: "12:30",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-purnima",
    rsvp_enabled: true,
    rsvp_count: 35,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-6",
    title: "Community Annadanam",
    description:
      "Monthly community meal service open to all. Volunteer to cook and serve or simply join us for a blessed meal.",
    event_type: "community",
    start_date: "2026-03-22",
    end_date: null,
    start_time: "12:00",
    end_time: "14:00",
    location: "RNHT Dining Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-4th-sunday",
    rsvp_enabled: true,
    rsvp_count: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-7",
    title: "Hanuman Jayanti",
    description:
      "Grand celebration of Lord Hanuman's birth with special Abhishekam, Sundara Kandam Parayanam, and cultural events.",
    event_type: "festival",
    start_date: "2026-04-13",
    end_date: "2026-04-13",
    start_time: "06:00",
    end_time: "21:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 55,
    created_at: new Date().toISOString(),
  },
];

export const samplePanchangam = {
  date: new Date().toISOString().split("T")[0],
  location: "Austin, TX",
  sunrise: "6:22 AM",
  sunset: "6:01 PM",
  tithi: {
    name: "Dwadashi",
    start: "3:45 AM",
    end: "2:12 AM (next day)",
    paksha: "Shukla",
  },
  nakshatra: {
    name: "Pushya",
    start: "11:23 PM (prev day)",
    end: "10:45 PM",
  },
  yoga: {
    name: "Siddha",
    start: "6:15 AM",
    end: "4:33 AM (next day)",
  },
  karana: {
    name: "Baalava",
    start: "3:45 AM",
    end: "3:02 PM",
  },
  rahu_kalam: {
    start: "10:42 AM",
    end: "12:12 PM",
    warning: true,
  },
  yama_gandam: {
    start: "3:12 PM",
    end: "4:42 PM",
  },
  gulika_kalam: {
    start: "7:42 AM",
    end: "9:12 AM",
  },
  muhurtham: {
    name: "Abhijit Muhurtham",
    start: "11:47 AM",
    end: "12:37 PM",
  },
  festival: null as { name: string; description: string } | null,
  vaara: "Wednesday",
  masa: "Phalguna",
  samvatsara: "Krodhana",
};
