import type { Service, ServiceCategory, Event } from "@/types/database";

export const sampleCategories: ServiceCategory[] = [
  {
    id: "cat-1",
    name: "Homam / Havan",
    slug: "homam-havan",
    description: "Sacred fire rituals and offerings to deities through Agni",
    icon: "🔥",
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Pooja Services",
    slug: "pooja-services",
    description: "Traditional worship rituals and prayers",
    icon: "🙏",
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "Kalyanotsavam",
    slug: "kalyanotsavam",
    description: "Celestial wedding ceremonies of deities",
    icon: "💒",
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Vrata / Katha",
    slug: "vrata-katha",
    description: "Sacred fasting and religious discourse services",
    icon: "📿",
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    name: "Astrology & Vastu",
    slug: "astrology-vastu",
    description: "Vedic astrology consultations and Vastu guidance",
    icon: "⭐",
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-6",
    name: "Temple Services",
    slug: "temple-services",
    description: "General temple rituals and darshan services",
    icon: "🛕",
    sort_order: 6,
    created_at: new Date().toISOString(),
  },
];

export const sampleServices: Service[] = [
  {
    id: "svc-1",
    category_id: "cat-2",
    name: "Archana",
    slug: "archana",
    short_description:
      "A devotional service invoking the deity by chanting their 108 or 1008 names.",
    full_description:
      "Archana is one of the most popular forms of worship where the priest chants the sacred names of the deity while offering flowers or kumkum. This service can be performed for any deity at the temple and is ideal for birthdays, special occasions, or regular worship.",
    significance:
      "Chanting the divine names purifies the mind, brings peace, and invokes the blessings of the deity for the devotee and their family.",
    items_to_bring: ["Flowers (optional)", "Fruits for offering"],
    whats_included: [
      "Chanting of 108 names",
      "Flower offering",
      "Prasadam distribution",
    ],
    image_url: null,
    price: 11,
    price_type: "fixed",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 15,
    location_type: "at_temple",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-2",
    category_id: "cat-2",
    name: "Abhishekam",
    slug: "abhishekam",
    short_description:
      "Sacred bathing ritual of the deity with milk, honey, yogurt, and other holy substances.",
    full_description:
      "Abhishekam is a powerful ritualistic bathing of the deity idol with sacred substances including milk, honey, curd, ghee, sugar water, turmeric water, sandalwood paste, and holy water. Each substance has deep spiritual significance and purifying properties.",
    significance:
      "Abhishekam cleanses the mind and soul of the devotee, washes away sins, and brings prosperity, health, and spiritual growth.",
    items_to_bring: [
      "Milk (1 gallon)",
      "Honey",
      "Yogurt",
      "New clothes for the deity (optional)",
    ],
    whats_included: [
      "Full abhishekam ritual",
      "Alankaram (decoration)",
      "Archana",
      "Prasadam",
    ],
    image_url: null,
    price: 51,
    price_type: "fixed",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 45,
    location_type: "at_temple",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-3",
    category_id: "cat-1",
    name: "Ganapathi Homam",
    slug: "ganapathi-homam",
    short_description:
      "Fire ritual dedicated to Lord Ganesha for removing obstacles and new beginnings.",
    full_description:
      "Ganapathi Homam is a sacred fire ritual performed to invoke the blessings of Lord Ganesha, the remover of obstacles. This is typically the first homam performed before any auspicious event or new beginning. The ritual involves chanting of Ganapathi mantras while making offerings into the sacred fire.",
    significance:
      "Lord Ganesha is worshipped first in any Hindu ritual. This homam removes obstacles, grants success in endeavors, and brings prosperity and wisdom.",
    items_to_bring: [
      "Modak or laddoo (21 pieces)",
      "Coconut",
      "Durva grass",
      "Red flowers",
    ],
    whats_included: [
      "Complete fire ritual",
      "All homa materials",
      "Sankalpam",
      "Purnahuti",
      "Prasadam",
    ],
    image_url: null,
    price: 101,
    price_type: "fixed",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-4",
    category_id: "cat-1",
    name: "Navagraha Homam",
    slug: "navagraha-homam",
    short_description:
      "Fire ritual to appease the nine planetary deities and reduce malefic planetary effects.",
    full_description:
      "Navagraha Homam is a powerful fire ritual performed to propitiate the nine celestial bodies (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu). This ritual helps mitigate the negative effects of planetary positions in one's horoscope.",
    significance:
      "The Navagraha Homam balances planetary influences, brings harmony, good health, prosperity, and helps overcome challenges caused by unfavorable planetary positions.",
    items_to_bring: [
      "9 types of grains",
      "9 types of flowers",
      "Coconut",
      "Ghee",
    ],
    whats_included: [
      "Full Navagraha ritual",
      "All homa materials",
      "Individual planet mantras",
      "Purnahuti",
      "Prasadam",
    ],
    image_url: null,
    price: 151,
    price_type: "fixed",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-5",
    category_id: "cat-3",
    name: "Sri Sita Rama Kalyanotsavam",
    slug: "sita-rama-kalyanotsavam",
    short_description:
      "Divine celestial wedding ceremony of Lord Rama and Goddess Sita.",
    full_description:
      "Experience the divine wedding of Lord Rama and Goddess Sita, one of the most beautiful and auspicious ceremonies in Hindu tradition. The ritual recreates the sacred wedding as described in the Ramayana, with Vedic mantras and elaborate decorations.",
    significance:
      "Witnessing and sponsoring the divine wedding brings marital harmony, blessings for family life, and spiritual merit. It symbolizes the ideal union of dharma and devotion.",
    items_to_bring: [
      "Flowers and garlands",
      "Fruits",
      "New clothes for deities (optional)",
    ],
    whats_included: [
      "Complete wedding ceremony",
      "Deity decoration",
      "Mangal sutra ceremony",
      "Talambralu",
      "Prasadam feast",
    ],
    image_url: null,
    price: null,
    price_type: "tiered",
    price_tiers: [
      {
        name: "Silver Sponsor",
        price: 251,
        description: "Name announced during ceremony, prasadam",
      },
      {
        name: "Gold Sponsor",
        price: 501,
        description:
          "Priority seating, name announced, special prasadam, deity photo",
      },
      {
        name: "Platinum Sponsor",
        price: 1001,
        description:
          "Front row seating, name on banner, special prasadam, deity photo, personalized blessing",
      },
    ],
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "at_temple",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-6",
    category_id: "cat-4",
    name: "Satyanarayana Vratam",
    slug: "satyanarayana-vratam",
    short_description:
      "Sacred worship of Lord Satyanarayana with Katha (story) recitation on Purnima.",
    full_description:
      "Sri Satyanarayana Vratam is a ritual performed on Purnima (full moon day) or on special occasions. The pooja involves worshipping Lord Vishnu in the form of Satyanarayana, followed by reading the five chapters of the Satyanarayana Katha. It is commonly performed for housewarmings, weddings, and other milestones.",
    significance:
      "This vratam bestows blessings of prosperity, harmony, and fulfillment. It is said to fulfill wishes, remove troubles, and bring peace to the household.",
    items_to_bring: [
      "Banana leaves",
      "Fruits and flowers",
      "Ripe bananas",
      "Jaggery and wheat flour (for prasadam)",
    ],
    whats_included: [
      "Pooja and Katha recitation",
      "All pooja materials",
      "Prasadam preparation guidance",
    ],
    image_url: null,
    price: 51,
    price_type: "fixed",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-7",
    category_id: "cat-5",
    name: "Muhoortham Consultation",
    slug: "muhoortham-consultation",
    short_description:
      "Vedic auspicious date and time calculation for important life events.",
    full_description:
      "Get personalized Muhoortham (auspicious timing) calculations from our experienced priest for weddings, griha pravesham, naming ceremonies, business openings, and other significant life events. The consultation considers your birth chart, planetary positions, and Panchangam data.",
    significance:
      "Starting important activities at an auspicious time ensures success, removes obstacles, and aligns your actions with cosmic energies for the best outcomes.",
    items_to_bring: [
      "Birth details of all family members involved",
      "Preferred date range",
    ],
    whats_included: [
      "Personal consultation",
      "Written Muhoortham report",
      "Do's and Don'ts for the occasion",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 60,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-8",
    category_id: "cat-6",
    name: "Deity Darshan & Aarti",
    slug: "deity-darshan-aarti",
    short_description:
      "Daily darshan and aarti of all temple deities with prasadam.",
    full_description:
      "Visit the temple for a peaceful darshan of all enshrined deities followed by the morning or evening aarti ceremony. Feel the divine presence and receive blessed prasadam.",
    significance:
      "Darshan and aarti purify the heart, bring inner peace, and establish a direct connection with the divine. Regular darshan is considered highly meritorious.",
    items_to_bring: ["Flowers (optional)"],
    whats_included: ["Darshan of all deities", "Aarti", "Prasadam"],
    image_url: null,
    price: null,
    price_type: "donation",
    price_tiers: null,
    suggested_donation: 5,
    duration_minutes: 30,
    location_type: "at_temple",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "svc-9",
    category_id: "cat-2",
    name: "Gruhapravesam",
    slug: "gruhapravesam",
    short_description:
      "Housewarming ceremony to purify and bless a new home with divine energies.",
    full_description:
      "Gruhapravesam is the sacred ceremony of entering a new home for the first time. The ritual includes Ganapathi Pooja, Vastu Pooja, Navagraha Pooja, and Havan to cleanse and energize the new home with positive vibrations.",
    significance:
      "This ceremony removes negative energies, invites prosperity, health, and happiness into the new home, and seeks divine blessings for the family.",
    items_to_bring: [
      "New pot with mango leaves",
      "Rice",
      "Turmeric and kumkum",
      "Milk to boil",
      "Coconuts",
    ],
    whats_included: [
      "Ganapathi Pooja",
      "Vastu Pooja",
      "Navagraha Shanti",
      "Havan",
      "Milk boiling ceremony",
    ],
    image_url: null,
    price: null,
    price_type: "tiered",
    price_tiers: [
      {
        name: "Basic",
        price: 201,
        description: "Core gruhapravesam ceremony (2 hours)",
      },
      {
        name: "Standard",
        price: 351,
        description:
          "Full ceremony with Navagraha Shanti and Vastu Pooja (3 hours)",
      },
      {
        name: "Premium",
        price: 501,
        description:
          "Complete ceremony with Havan, all poojas, and extended rituals (4+ hours)",
      },
    ],
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "outside_temple",
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const sampleEvents: Event[] = [
  {
    id: "evt-1",
    title: "Ugadi Celebrations 2026",
    description:
      "Telugu and Kannada New Year celebrations with special poojas, cultural programs, and festive feast. Join us for Panchangam Sravanam and Ugadi Pachadi distribution.",
    event_type: "festival",
    start_date: "2026-03-29",
    end_date: "2026-03-29",
    start_time: "09:00",
    end_time: "14:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 45,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-2",
    title: "Sri Rama Navami",
    description:
      "Celebration of Lord Rama's birth with Sita Rama Kalyanotsavam, Abhishekam, and special cultural programs throughout the day.",
    event_type: "festival",
    start_date: "2026-04-07",
    end_date: "2026-04-07",
    start_time: "08:00",
    end_time: "20:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 78,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-3",
    title: "Weekly Bhajan Sandhya",
    description:
      "Join us every Saturday evening for devotional bhajans and kirtans. All are welcome to participate and immerse in the divine melodies.",
    event_type: "regular_pooja",
    start_date: "2026-03-14",
    end_date: null,
    start_time: "18:00",
    end_time: "19:30",
    location: "RNHT Prayer Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-saturday",
    rsvp_enabled: false,
    rsvp_count: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-4",
    title: "Yoga & Meditation Session",
    description:
      "Weekly yoga and meditation classes suitable for all levels. Guided by certified instructors combining traditional and modern techniques.",
    event_type: "class",
    start_date: "2026-03-15",
    end_date: null,
    start_time: "07:00",
    end_time: "08:30",
    location: "RNHT Community Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-sunday",
    rsvp_enabled: true,
    rsvp_count: 22,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-5",
    title: "Monthly Satyanarayana Vratam",
    description:
      "Join the community for the monthly Satyanarayana Pooja on Purnima (Full Moon) day. Katha recitation followed by maha prasadam.",
    event_type: "regular_pooja",
    start_date: "2026-03-25",
    end_date: null,
    start_time: "10:00",
    end_time: "12:30",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-purnima",
    rsvp_enabled: true,
    rsvp_count: 35,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-6",
    title: "Community Annadanam",
    description:
      "Monthly community meal service open to all. Volunteer to cook and serve or simply join us for a blessed meal.",
    event_type: "community",
    start_date: "2026-03-22",
    end_date: null,
    start_time: "12:00",
    end_time: "14:00",
    location: "RNHT Dining Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-4th-sunday",
    rsvp_enabled: true,
    rsvp_count: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: "evt-7",
    title: "Hanuman Jayanti",
    description:
      "Grand celebration of Lord Hanuman's birth with special Abhishekam, Sundara Kandam Parayanam, and cultural events.",
    event_type: "festival",
    start_date: "2026-04-13",
    end_date: "2026-04-13",
    start_time: "06:00",
    end_time: "21:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 55,
    created_at: new Date().toISOString(),
  },
];

export const samplePanchangam = {
  date: new Date().toISOString().split("T")[0],
  location: "Las Vegas, NV",
  sunrise: "6:22 AM",
  sunset: "6:01 PM",
  tithi: {
    name: "Dwadashi",
    start: "3:45 AM",
    end: "2:12 AM (next day)",
    paksha: "Shukla",
  },
  nakshatra: {
    name: "Pushya",
    start: "11:23 PM (prev day)",
    end: "10:45 PM",
  },
  yoga: {
    name: "Siddha",
    start: "6:15 AM",
    end: "4:33 AM (next day)",
  },
  karana: {
    name: "Baalava",
    start: "3:45 AM",
    end: "3:02 PM",
  },
  rahu_kalam: {
    start: "10:42 AM",
    end: "12:12 PM",
    warning: true,
  },
  yama_gandam: {
    start: "3:12 PM",
    end: "4:42 PM",
  },
  gulika_kalam: {
    start: "7:42 AM",
    end: "9:12 AM",
  },
  muhurtham: {
    name: "Abhijit Muhurtham",
    start: "11:47 AM",
    end: "12:37 PM",
  },
  festival: null as { name: string; description: string } | null,
  vaara: "Wednesday",
  masa: "Phalguna",
  samvatsara: "Krodhana",
};
